# Generated by Django 4.2.5 on 2023-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PATH', models.CharField(max_length=255)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('NAME', models.CharField(max_length=255)),
            ],
        ),
    ]
