# Generated by Django 4.2.5 on 2023-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='IMAGE',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
