# Generated by Django 4.2.5 on 2023-09-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_form_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='PATH',
            new_name='PDF',
        ),
    ]
