# Generated by Django 4.2.5 on 2023-09-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_path_form_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='CREATED_AT',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='IMAGE',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='PDF',
            new_name='pdf',
        ),
    ]
